---
- name: install tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python-mysqldb
  tags:
  - packages

- name: install mysql-server
  apt:
    name: mysql-server
    state: present
  tags:
  - packages

- name: set hostname to servername
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
  - hostname

- name: setup root config
  template:
    src: .my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    mode: 0644
  tags:
  - configure

- name: ensure mysql listing on all ports
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mysql
  tags:
  - configure

- name: ensure mysql started
  service:
    name: mysql
    state: started
    enabled: yes
  tags:
  - service

- name: create user
  mysql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_pass }}"
    priv: "{{ db_name }}.*:ALL"
    host: "{{ db_user_host }}"
    state: present
  tags:
  - configure

- name: create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
  tags:
  - configure

- name: ensure mysql started
  service:
    name: mysql
    state: started
    enabled: yes
  tags:
  - service
